How to Use Tensorflow for Classification
---

[![](https://i.ytimg.com/vi/4urPuRoT1sE/hqdefault.jpg)](https://youtu.be/4urPuRoT1sE?list=PL2-dafEMk2A7YdKv4XfKpfbTH5z6rEEj3)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

/home/dillon/projects/line-art-gan/env/lib/python3.7/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
df = pd.read_csv('data.csv')
print(df.head())
print()
df = df.drop(['index', 'price', 'sq_price'], axis=1) # dropping useless columns
df = df[0:10] # only the first 10 rows
df

   index    area  bathrooms     price    sq_price
0      0  2104.0        3.0  399900.0  190.066540
1      1  1600.0        3.0  329900.0  206.187500
2      2  2400.0        3.0  369000.0  153.750000
3      3  1416.0        2.0  232000.0  163.841808
4      4  3000.0        4.0  539900.0  179.966667



area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [3]:
# assisgning good (1) & bad (2) buys
df.loc[:, ('y1')] = [1,1,1,0,0,1,0,1,1,1]
# y2 is assigned as the opposite of y1 but as true/false
df.loc[:, ('y2')] = df['y1'] == 0
# y2 is converted to int values
df.loc[:, ('y2')] = df['y2'].astype(int)
df

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [4]:
#input X & Y converted to matricies (2D numpy arrays)
input_x = df.loc[:, ['area', 'bathrooms']].to_numpy()
input_y = df.loc[:, ['y1', 'y2']].to_numpy()

In [5]:
input_x

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00],
       [1.534e+03, 3.000e+00],
       [1.427e+03, 3.000e+00],
       [1.380e+03, 3.000e+00],
       [1.494e+03, 3.000e+00]])

In [6]:
input_y

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [8]:
# hyper params  
learning_rate = 0.000001
epochs = 2000
display_steps = 50
n_samples = input_y.size

In [10]:
x = tf.placeholder(tf.float32, [None,2])

# 2x2 float matrix for the weights
W = tf.Variable(tf.zeros([2,2]))

# biases for better fitting
B = tf.Variable(tf.zeros([2]))

y_vals = tf.add(tf.matmul(x, W), B)

y = tf.nn.softmax(y_vals)

y_ = tf.placeholder(tf.float32, [None, 2])

In [11]:
cost = tf.reduce_sum(tf.pow(y_ - y, 2)) / (2 * n_samples)

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [13]:
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [20]:
for i in range(epochs):
    sess.run(optimizer, feed_dict={x: input_x, y_: input_y})
    
    if i % display_steps == 0:
        cc = sess.run(cost, feed_dict={x: input_x, y_: input_y})
        print('Training step:', '%04d' % i, 'cost=', '{:.9f}'.format(cc))
        
print("optimization finished")
training_cost = sess.run(cost, feed_dict={x: input_x, y_: input_y})
print("Training cost=", training_cost, 'W=', sess.run(W), 'B=', sess.run(B))

Training step: 0000 cost= 0.114958666
Training step: 0050 cost= 0.109539948
Training step: 0100 cost= 0.109539881
Training step: 0150 cost= 0.109539807
Training step: 0200 cost= 0.109539740
Training step: 0250 cost= 0.109539665
Training step: 0300 cost= 0.109539591
Training step: 0350 cost= 0.109539531
Training step: 0400 cost= 0.109539464
Training step: 0450 cost= 0.109539390
Training step: 0500 cost= 0.109539330
Training step: 0550 cost= 0.109539263
Training step: 0600 cost= 0.109539188
Training step: 0650 cost= 0.109539129
Training step: 0700 cost= 0.109539054
Training step: 0750 cost= 0.109538995
Training step: 0800 cost= 0.109538913
Training step: 0850 cost= 0.109538853
Training step: 0900 cost= 0.109538786
Training step: 0950 cost= 0.109538712
Training step: 1000 cost= 0.109538652
Training step: 1050 cost= 0.109538570
Training step: 1100 cost= 0.109538510
Training step: 1150 cost= 0.109538436
Training step: 1200 cost= 0.109538376
Training step: 1250 cost= 0.109538309
Training ste

In [21]:
sess.run(y, feed_dict={x: input_x})

array([[0.7112523 , 0.28874776],
       [0.66498977, 0.33501023],
       [0.73657656, 0.26342347],
       [0.6471879 , 0.3528121 ],
       [0.78335613, 0.21664388],
       [0.7006948 , 0.29930523],
       [0.6586633 , 0.34133676],
       [0.6482863 , 0.35171372],
       [0.6436828 , 0.35631716],
       [0.6548012 , 0.34519887]], dtype=float32)

In [ ]:
# looks like all homes are a good buy, need to add hidden layer